
public class PowerPlant extends Building {//subclass 
	public PowerPlant(String name, int power) {
		super(name, -power);//since it consumes a negative amount of power
	}

	@Override
	public void morePower(int amount) {
		setPower(getPower() - amount);//becomes more negative
	}

	public static void testPowerPlant() {
		PowerPlant p = new PowerPlant("UIC Power Plant", 1000000);
		System.out.println(p.getName() == "UIC Power Plant");
		System.out.println(p.getPower() == -1000000);
		p.setPower(-2000000); // Sets the power consumed by the power plant.
		System.out.println(p.getPower() == -2000000);
		p.morePower(500000); // Increases the power generated by the power plant.
		System.out.println(p.getPower() == -2500000);
		p.morePower(-2510000); // Turn off the power plant: it now consumes electricity.
		System.out.println(p.getPower() == 10000);
	}
}
